therapeutics/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='index'),
    path('special/',views.special,name='special'),
    path('users/',include('users.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('users/<int:id>/my_profile/', views.settings, name='settings'),
    path('sub_level/', views.sub_level, name='sub_level'),
    path('level_questions/', views.level_question, name='level_question'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):

    GENDER_CHOICES = [
        ('Fe', 'Female'),
        ('Ma', 'Male'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(auto_now=False, auto_now_add=False)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=50)
    grade = models.CharField(max_length=20)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','first_name','last_name')
        # labels = {
        #     "date_joined": "Setup Timing",
        # }

class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfile
        fields = ('dob','gender','grade','profile_pic')

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from users.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import UserProfile

# Create your views here.
def index(request):
    return render(request, 'users/index.html')

def settings(request, id):
    profile_record = get_object_or_404(UserProfile, id=id)
    form = UserProfileForm(request.POST or None, instance=profile_record)
    
    user_record = get_object_or_404(User, id=profile_record.user_id)
    user_form = UserForm(request.POST or None, instance=user_record)

    if form.is_valid() and user_form.is_valid():
        form.save()
        user_form.save()
        return redirect("../../../")
    else:
        form = UserProfileForm(instance=profile_record)   
        user_form = UserForm(instance=user_record)    
    context = {'form': form, 'user_form': user_form} 
    return render(request, 'users/settings.html', context)

def sub_level(request):
    # my_record = UserProfile.objects.get()
    return render(request, 'users/sub_level.html')

def level_question(request):
    return render(request, 'users/level_questions.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged in !")  

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user_form.cleaned_data['password'])
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request,'users/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        print(user)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'users/login.html', {})

templates/users/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Edu Therapeutics</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
        integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous">
    </script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
        integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous">
    </script>

    <link rel="stylesheet" href="/static/css/login.css">
    <link rel="stylesheet" href="/static/css/dashboard.css">

    {% block style_files %}{% endblock %}

</head>
  <body>
    
    {% block login_block %}{% endblock %}

    {% block body_block %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>

    <script>
        $(document).ready(function () {
            $("#sidebarCollapse").on("click", function () {
                $("#sidebar").toggleClass("active");
                $;
            });
        });
    </script>

    {% block script_codes %}{% endblock %}
  </body>
</html>

templates/users/index.html
{% extends "users/base.html" %}
{% block body_block %}
{% if user.is_authenticated %}
<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <!-- <h3>Sidebar</h3> -->
            <img class="logo" src="/static/images/logo.png" alt="EduTherapeutics" />
            <strong>EDU</strong>
        </div>

        <div class="user-section">
            {% if user.userprofile.profile_pic %}
                <img class="user-profile" src="{{user.userprofile.profile_pic.url}}" alt="user-avatar" />
            {% else %}
                <img class="user-profile" src="/static/images/avatar.png" alt="user-avatar" />
            {% endif %}
            <div class="detail">
                <span class="avatar-title">{{user.username}}</span><br />
                <span class="category">Student</span>
            </div>
        </div>

        <ul class="list-unstyled components">
            <li class="active">
                <a href="/">
                    <i class="fas fa-home"></i>
                    <span class="side-menu-link">Dashboard</span>
                </a>         
            </li>
        </ul>
    </nav>

    <!-- Page Content  -->
    <div id="content">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <button type="button" id="sidebarCollapse" class="btn btn-default">
                    {% comment %} <i class="fas fa-align-left"></i> {% endcomment %}
                    <i class="fas fa-bars"></i>

                    <!-- <span>Menu</span> -->
                </button>
                <div class="nav-link mr-auto ml-2">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fas fa-search"></i>
                            </span>
                        </div>
                        <input type="text" class="form-control search" placeholder="Search" aria-label="Search">
                    </div>
                </div>
                <div class="nav-link ml-auto">
                    <div class="dropdown">
                        {% if user.userprofile.profile_pic %}
                            <img class="user-profile" src="{{user.userprofile.profile_pic.url}}" alt="user-avatar" />
                        {% else %}
                            <img class="user-profile" src="/static/images/avatar.png" alt="user-avatar" />
                        {% endif %}
                        <img style="width: 12px;" src="/static/images/chevron.png">
                        <div class="dropdown-content">
                            <a href="/users/{{user.userprofile.id}}/my_profile/"><i style="color: #392c70;" class="fas fa-cog"></i> Settings</a>
                            <a href="/logout/"><i style="color: #392c70;" class="fas fa-sign-out-alt" aria-hidden="true"></i> Logout</a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>

        <div class="custom-row">
            <div class="page-header container-fluid">
                <h6 class="page-sub-title">Hello, {{user.username}}</h6>
                <h3 class="page-title">
                    Courses List
                </h3>
            </div>
        </div>

        <div class="custom-row">
            <div class="col-xl-4 col-lg-6 col-md-6 col-12">
                <div class="main">
                    <h2>Level 1</h2>
                    <p>Sub-Levels: 29</p>
                    <a href="/sub_level/">Continue</a>
                </div>
            </div>

            <div class="col-xl-4 col-lg-6 col-md-6 col-12">
                <div class="main">
                    <h2>Level 2</h2>
                    <p>Sub-Levels: 29</p>
                    <a href="#">Continue</a>
                </div>
            </div>

            <div class="col-xl-4 col-lg-6 col-md-6 col-12">
                <div class="main">
                    <h2>Level 3</h2>
                    <p>Sub-Levels: 3</p>
                    <a href="#">Continue</a>
                </div>
            </div>

            <div class="col-xl-4 col-lg-6 col-md-6 col-12">
                <div class="main">
                    <h2>Level 4</h2>
                    <p>Sub-Levels: 4</p>
                    <a href="#">Continue</a>
                </div>
            </div>

            <div class="col-xl-4 col-lg-6 col-md-6 col-12">
                <div class="main">
                    <h2>Level 5</h2>
                    <p>Sub-Levels: 3</p>
                    <a href="#">Continue</a>
                </div>
            </div>
        </div>

        
    </div>
</div>
{% else %}
    <div style="text-align:center;margin:50px auto;">
        <h2>Register or Login if you'd like to</h2>
        {% comment %} <a>Register</a> {% endcomment %}
        <a href="/users/user_login/">Login</a>
    </div>
{% endif %}
{% endblock %}

templates/users/level_questions.html
{% extends "users/base.html" %}
{% block style_files %}
    <link rel="stylesheet" href="/static/css/levels.css">
{% endblock %}
{% block body_block %}
{% if user.is_authenticated %}
<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <!-- <h3>Sidebar</h3> -->
            <img class="logo" src="/static/images/logo.png" alt="EduTherapeutics" />
            <strong>EDU</strong>
        </div>

        <div class="user-section">
            {% if user.userprofile.profile_pic %}
                <img class="user-profile" src="{{user.userprofile.profile_pic.url}}" alt="user-avatar" />
            {% else %}
                <img class="user-profile" src="/static/images/avatar.png" alt="user-avatar" />
            {% endif %}
            <div class="detail">
                <span class="avatar-title">{{user.username}}</span><br />
                <span class="category">Student</span>
            </div>
        </div>

        <ul class="list-unstyled components">
            <li class="active">
                <a href="/">
                    <i class="fas fa-home"></i>
                    <span class="side-menu-link">Dashboard</span>
                </a>         
            </li>
        </ul>
    </nav>

    <!-- Page Content  -->
    <div id="content">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <button type="button" id="sidebarCollapse" class="btn btn-default">
                    {% comment %} <i class="fas fa-align-left"></i> {% endcomment %}
                    <i class="fas fa-bars"></i>

                    <!-- <span>Menu</span> -->
                </button>
                <div class="nav-link mr-auto ml-2">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fas fa-search"></i>
                            </span>
                        </div>
                        <input type="text" class="form-control search" placeholder="Search" aria-label="Search">
                    </div>
                </div>  
                <div class="nav-link ml-auto">
                    <div class="dropdown">
                        {% if user.userprofile.profile_pic %}
                            <img class="user-profile" src="{{user.userprofile.profile_pic.url}}" alt="user-avatar" />
                        {% else %}
                            <img class="user-profile" src="/static/images/avatar.png" alt="user-avatar" />
                        {% endif %}
                        <img style="width: 12px;" src="/static/images/chevron.png">
                        <div class="dropdown-content">
                            <a href="/users/{{user.userprofile.id}}/my_profile/"><i style="color: #392c70;" class="fas fa-cog"></i> Settings</a>
                            <a href="/logout/"><i style="color: #392c70;" class="fas fa-sign-out-alt" aria-hidden="true"></i> Logout</a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>

        <div class="custom-row">
            <div class="page-header container-fluid">
                <h3 class="page-title">
                    Level 1.1 Introduction Task
                </h3>
                <a class="float-right" href="/sub_level/"><input type="button" class="btn btn-primary" value="Sub Levels"></a>
            </div>
        </div>

        <div class="course_wrap">
            <input type="hidden" class="studentId" value="65">
            <div class="custom-row">
                <div class="col-sm-10 offset-sm-1">
                    <div class="level_detail_wrap">
                        <div class="top_content">
                            <div class="row info">
                                <div class="col-xl-8 col-lg-12 order-2 order-xl-1">
                                    <div class="content_bx">
                                        <h3>
                                        Level 1.1 Introduction Task
                                        </h3>
                                        <p></p><p><strong>Trainer Instructions</strong></p>
                                        <p>1. Trainer voice says sound of symbol while Student looks at the screen.</p>
                                        <p>2. Student repeats sound and Trainer presses NEXT to go to the next symbol.</p>
                                        <p>3. Trainer will have Student repeat the exercise multiple times with Trainer voice.</p>
                                        <p>4. Trainer can repeat activity and have Student say the sound without verbal prompt.</p><p></p>
                                        <div class="btn_opt mt-3">
                                            <input type="hidden" class="sub_level_ids" value="1">
                                            <a href="javascript:void(0);" id="lets_start" level-id="1">Let's Go</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-lg-12 order-1 order-xl-2">
                                    <div class="imgbx">
                                        <img width="100%" src="https://edu-therapeutics.com/lap/public/frontend/images/others/styudy-boy.jpg">
                                    </div>
                                </div>
                            </div>
                            <!-- Questions -->
                            <div style="display: none;" class="row quiz">
                                <div class="col-xl-12 col-lg-12 order-2 order-xl-1">
                                    <div class="progress details_progressbar">
                                        <div class="progress-bar-q" style="width:100%; border-radius: 3px ;" aria-valuemax="100"></div>
                                    </div>
                                    <div class="content_bx_q middle_content2">
                                        <div class="bottom_btn d-md-flex justify-content-md-between ques_btn next-prev-btn">
                                            <div class="arrow-left left prev" onclick="plusSlides(-1)" id="prev-question-level-func" sub-lev="1" prev="1" data-attr="1">
                                                <i class="fa fa-angle-left"></i>
                                            </div>

                                            <div class="arrow-left right" onclick="plusSlides(1)" id="next-question-level" data-attr="1" sub-lev="1" cur="2">
                                                <i class="fa fa-angle-right"></i>
                                            </div>
                                        </div>         
                                        <div class="slideshow-container">                                        
                                            <div class="mySlides">
                                                <p class="ans">a</p>
                                            </div>
                                            <div class="mySlides">
                                                <p class="ans">m</p>
                                            </div>
                                            <div class="mySlides">
                                                <p class="ans">t</p>
                                            </div>
                                            <div class="mySlides">
                                                <p class="ans">f</p>
                                            </div>
                                            <div class="mySlides">
                                                <p class="ans">i</p>
                                            </div>
                                            <div class="mySlides">
                                                <p class="ans">b</p>
                                            </div>
                                            <div class="mySlides">
                                                <p class="ans">s</p>
                                            </div>                                            
                                        </div>    
                                        <div class="levelup">
                                            <img src="/static/images/thumbs-up.png" >
                                            <h3 class="fin">Congrats! Your level has been completed.</h3>
                                        </div>                                                             
                                    </div>
                                    
                                    <div class="bottom_btn d-flex ques_btn next-prev-btn">
                                        <a href="/level_questions/" class="mr-auto btn-redo">Redo</a>
                                        <a href="/sub_level/" class="ml-auto btn-complete">Complete Later</a>
                                        <a href="/sub_level/" class="ml-auto btn-done">Done</a>
                                    </div>
                                </div>                        
                            </div>
                        </div>
                            <div id="question-data"></div>
                            <div class="audio_player mt-3">

                            <audio autoplay="" controlslist="nodownload" loop="" id="vid" style="width: 100%;">
                                <source src="https://lap.edu-therapeutics.com/public/audio/1573537973_Asilomar .wav" type="audio/wav">
                            </audio>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>
{% else %}
    <h2>Register or Login if you'd like to</h2>
{% endif %}
{% endblock %}

{% block script_codes %}
<script>
    $(document).ready(function(){
        $('.btn-redo').hide();        
        $('.btn-done').hide(); 

        $('#lets_start').on('click', function(){
            $('.top_content').css('background', '#ffffff')
            $('.info').hide();
            $('.quiz').show();
        });

        $('.ans').on('click', function(e){
            $(this).css('font-weight', 'bold');
        });
    });
</script>

<script>
    var slideIndex = 1;
    showSlides(slideIndex);

    function plusSlides(n) {
        showSlides(slideIndex += n);
    }

    function currentSlide(n) {
        showSlides(slideIndex = n);
    }

    function showSlides(n) {
        var i;
        var scon = document.getElementsByClassName("slideshow-container");
        var slides = document.getElementsByClassName("mySlides");
        if (n > slides.length) {slideIndex = 1}    
        if (n < 1) {slideIndex = slides.length}
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";  
        }
        slides[slideIndex-1].style.display = "block";  
        if (n == slides.length + 1) { 
            console.log('finish');
            $('.slideshow-container').hide();
            $('.levelup').show();
            $('.left').hide();
            $('.right').hide();
            $('.btn-complete').hide();        
            $('.btn-redo').show();        
            $('.btn-done').show();        
        }
    }
</script>
{% endblock %}

templates/users/login.html
{% extends 'users/base.html' %}
{% block login_block %}
<header>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">            
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active"
                style="background-image: url('/static/images/11.jpg')">                    
            </div>
            <div class="carousel-item" style="background-image: url('/static/images/13.jpg')">                
            </div>
            <div class="carousel-item" style="background-image: url('/static/images/14.jpg')">                
            </div>
        </div>           
    </div>
    <div class="login_box">
        <img class="logo_x" src="/static/images/logo-x.png" alt="logo">
        <form method="post" id="frm" action="{% url 'users:user_login' %}">
            {% csrf_token %}
            <div class="form-group">
                <input id="email" type="text" class="form-control" name="username" placeholder="Email/Username" value="" required="" autofocus="">
            </div>
            <div class="form-group">
                <input id="password" type="password" class="form-control" placeholder="Password" name="password" required="">
            </div>
            {% comment %} <div class="form-group">
                <input type="hidden" name="g-recaptcha-response">            
            </div> {% endcomment %}
            <div class="text-left">
                <a href="#" class="btn_link">Forgot Password?</a>
            </div>
            <div class="text-center btn_optn">
                <input class="btn btn-info btn-md btn-block btn_design" type="submit" name="" value="Login">
            </div>                
        </form>
    </div>
</header>
{% endblock %}

templates/users/registration.html
{% extends "users/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/users/settings.html
{% extends "users/base.html" %}
{% block body_block %}
{% if user.is_authenticated %}
<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <!-- <h3>Sidebar</h3> -->
            <img class="logo" src="/static/images/logo.png" alt="EduTherapeutics" />
            <strong>EDU</strong>
        </div>

        <div class="user-section">
            {% if user.userprofile.profile_pic %}
                <img class="user-profile" src="{{user.userprofile.profile_pic.url}}" alt="user-avatar" />
            {% else %}
                <img class="user-profile" src="/static/images/avatar.png" alt="user-avatar" />
            {% endif %}
            <div class="detail">
                <span class="avatar-title">{{user.username}}</span><br />
                <span class="category">Student</span>
            </div>
        </div>

        <ul class="list-unstyled components">
            <li class="active">
                <a href="/">
                    <i class="fas fa-home"></i>
                    <span class="side-menu-link">Dashboard</span>
                </a>         
            </li>
        </ul>
    </nav>

    <!-- Page Content  -->
    <div id="content">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <button type="button" id="sidebarCollapse" class="btn btn-default">
                    {% comment %} <i class="fas fa-align-left"></i> {% endcomment %}
                    <i class="fas fa-bars"></i>

                    <!-- <span>Menu</span> -->
                </button>
                <div class="nav-link mr-auto ml-2">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="fas fa-search"></i>
                            </span>
                        </div>
                        <input type="text" class="form-control search" placeholder="Search" aria-label="Search">
                    </div>
                </div>
                <div class="nav-link ml-auto">
                    <div class="dropdown">
                        {% if user.userprofile.profile_pic %}
                            <img class="user-profile" src="{{user.userprofile.profile_pic.url}}" alt="user-avatar" />
                        {% else %}
                            <img class="user-profile" src="/static/images/avatar.png" alt="user-avatar" />
                        {% endif %}
                        <img style="width: 12px;" src="/static/images/chevron.png">
                        <div class="dropdown-content">
                            <a href="#"><i style="color: #392c70;" class="fas fa-cog"></i> Settings</a>
                            <a href="/logout/"><i style="color: #392c70;" class="fas fa-sign-out-alt" aria-hidden="true"></i> Logout</a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>

        <div class="custom-row">
            <div class="page-header container-fluid">
                <h3 class="page-title">
                    My Profile
                </h3>
            </div>
            <form action="" method="POST" class="user_form m-auto">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        {{ user_form.as_table }}
                    </div>
                    <div class="col-md-6">
                        {{ form.as_table }}
                    </div>
                </div>
                {% if user.userprofile.profile_pic %}
                    <img src="{{user.userprofile.profile_pic.url}}">
                {% else %}
                    <img src="/static/images/avatar.png">
                {% endif %}
                <br><br>
                <input class="btn-primary" type="submit" value="Update">
            </form>
        </div>
        
    </div>
</div>
{% else %}
    <h2>Register or Login if you'd like to</h2>
{% endif %}
{% endblock %}